---
output:
  pdf_document:
    latex_engine: xelatex
    fig_caption: yes
  word_document: default
mainfont: Palatino
header-includes:
- \usepackage{caption}
- \captionsetup[figure]{labelformat=empty}
- \pagenumbering{gobble}
---


<center>

![
**Figure 1. Experimental designs of this study**. **a** Experiment I. Effects of the indexing method were tested. A 1st PCR indexing protocol appends sample-specific index sequences in the 1st PCR using “1st-indexing-1st-PCR primers” while a 2nd PCR indexing protocol appends the index sequences in the 2nd PCR using “2nd-indexing-2nd PCR primers.” “Purification” indicates magnetic beads purification in Experiment I. **b** Experiment II. Effects of exonuclease purification on index-hopping events were tested. Exonuclease purification was performed for each sample. Then samples were combined and incubated to test the effects of incubation time and temperature. **c** Experiment III. The effects of the 1st PCR replicates and template DNA volume were tested. Other processes were identical with that of Experiment II with exonuclease purification.
](00_FormattedFigs/Figure_01.pdf){width=85%}

</center>

<center>

![
**Figure 2. Nonmetric dimensional scaling (NMDS) and Bray-Curtis dissimilarities of fish eDNA composition detected in Experiment I.** Fish eDNA compositions of (**a**) seawater samples collected in Nagahama, Kyoto, Japan, (**b**) seawater samples collected in Otoumi, Fukui, Japan, (**c**) freshwater samples collected in Seta River, Otsu, Japan, and (**d**) a mixture of 10 standard fish DNAs. Filled circles and triangles indicate that KAPA HiFi HotStart ReadyMix and Platinum SuperFi II PCR Master Mix was used for PCR, respectively. Red and blue circles indicate that sample-specific index sequences were appended by the 1st PCR indexing method and the 2nd PCR indexing method, respectively. (**e**) Each panel represents eDNA samples collected in one study site. Points in each panel represent Bray-Curtis dissimilarities of fish eDNA compositions between two eDNA samples. The thick bar indicates the median value of the Bray-Curtis dissimilarities in each treatment. Statistical clarity was tested by bootstrap test (see Methods).
](00_FormattedFigs/Figure_02.pdf){width=90%}

</center>




<center>

![
**Figure 3. The estimation of the index-hopping probability of each library preparation method.** $y$-axis indicates the proportion of sequence reads for each OTU generated by index-hopping. We used three index combinations in Experiment II, i.e., ID1_F (AACTTTCC)-ID1_R (AACTTTCC) (positive sample), ID2_F (GTATCCTA)-ID2_R (GTATCCTA) (H~2~O), and ID3_F (AGCGGACG)-ID3_R (AGCGGACG) (H~2~O). Index-hopping is defined as the occurrence of any of the four “unused” index combinations in this study: ID1_F-ID2_R, ID1_F-ID3_R, ID2_F-ID1_R, and ID3_F-ID1_R. We ignored the other possible combinations as described in the main text. Each point represent the index-hopped sequence reads for each OTU divided by the sequence reads of the corresponding OTU detected in the positive sample. Blue and light blue points indicate that exonuclease-purified 1st PCR products were pooled and incubated on ice and at room temperature (22$^{\circ}$C), respectively. Red and dark red points indicate not-purified 1st PCR products were pooled and incubated on ice and at room temperature (22$^{\circ}$C), respectively.
](00_FormattedFigs/Figure_03.pdf){width=100%}

</center>


<center>

![
**Figure 4. Effects of the number of replicates and the volume of template DNA in the 1st PCR reaction on community compositions and OTU richness.** (**a**, **b**) Effects of the number of replicates and the template DNA volume on the number of fish OTUs in the Sea_Nagahama samples (**a**) and standard DNA samples (**b**). In **b**, Dashed horizontal line indicates the number of standard DNAs included in the reactions. Statistical clarity was tested by GLM. (**c**, **d**) Effects of the number of replicates and the template DNA volume on Bray-Curtis dissimilarities in the Sea_Nagahama samples (**c**) and standard DNA samples (**d**). Statistical clarity was tested by the bootstrap analysis. (**e**, **f**) The relationship between the relative abundance of OTUs and detected treatments. In e, each point indicates that each OTU is newly detected in the replication treatment described on $x$-axis. Points at “Detected OTUs in 1-rep.” indicate all OTUs detected in the 1-rep. treatment. Colors indicate the treatment in which OTUs are detected. (**f**) Results for the volume test of the Sea_Nagahama samples.
](00_FormattedFigs/Figure_04.pdf){width=90%}

</center>



<center>

![
**Figure 5. Effects of index sequences and protocols on the relative abundance and community compositions of fish detected in the Nagahama samples.** (**a**) $y$-axis shows the relative abundance of three most-dominant OTUs. $x$-axis shows library preparation method (= “2nd PCR indexing”) or the names of index sequence used in the 1st PCR. Red dashed horizontal lines indicate the mean relative abundance of each OTU detected by the 2nd PCR indexing method. In Experiment I, only one library was sequenced using each index. In Experiments II and III, multiple libraries were sequenced using the same index. Note that different experimental treatments (e.g., incubation time and temperature in Experiment II) are grouped in this figure. In Experiment III, statistical clarity was tested by GLM. (**b**) The effects of library preparation protocols on the fish community compositions of three study sites visualized by Nonmetric dimensional scaling (NMDS). All Nagahama samples are clearly distinguished from natural eDNA samples from the other study sites. Symbols and colors indicate the library preparation protocols and study sites, respectively. Ellipses indicate 95% confidential intervals for each study site. An NMDS plot with more detailed sample information is shown in Figure S5b.
](00_FormattedFigs/Figure_05.pdf){width=100%}

</center>


<center>

![
**Figure S1. Sequence reads generated in Experiment I (not normalized)**. Each panel shows sequence reads for 5 positive samples (R01-R05) and 1 negative sample (R06; H~2~O). Colors indicate fish family assigned by `Claident`, or the standard fish DNAs.
](00_FormattedFigs/Figure_S01.pdf){width=100%}

</center>



<center>

![
**Figure S2. Relative abundance and the number of OTUs detected in Experiment I.** (**a**) The number of OTUs detected in each treatment. $x$-axis indicates experimental protocols (i.e., the 1st or 2nd PCR indexing protocol and KAPA HiFi HostStart ReadyMix or Platinum SuperFi II PCR Master Mix). (**b**) Relative abundance of OTUs detected in each treatment. $x$-axis indicates replicates in the treatment. Colors indicate fish family assigned by `Claident`, or the standard fish DNAs.
](00_FormattedFigs/Figure_S02.pdf){width=90%}

</center>



<center>

![
**Figure S3. Effects of the library preparation methods on the detected relative abundance of the three most-dominant OTUs.** Results for (**a**) the most-dominant OTUs, (**b**) the second-most-dominant OTUs, and (**c**) the third-most-dominant OTUs. Note that the taxon that each OTU represents is different depending on the study site. Taxon name assigned to each OTU is shown at the top of each panel. Statistical clarity was tested by GLM that assumed normal distributions of the sequence reads (see Methods).
](00_FormattedFigs/Figure_S03.pdf){width=85%}

</center>



<center>

![
**Figure S4. Relative abundance of sequence reads detected in Experiment III. Each panel indicates 5 replicates for each treatment. Note that R01 in 1-rep. treatment in the replication test was removed because only 304 reads were assigned to the sample. Colors indicate fish family assigned by `Claident`, or the standard fish DNAs.
](00_FormattedFigs/Figure_S04.pdf){width=100%}

</center>



<center>

![
**Figure S5. Effects of library preparation protocols on the community composition of fish eDNA detected in the Nagahama samples.** (**a**) Relative abundance of sequence reads detected in the Nagahama samples. Each panel shows the indicated experimental treatment, and colors indicate fish family. (**b**) Nonmetric dimensional scaling (NMDS) of all natural eDNA samples analyzed in the present study. Various library preparation methods were tested for the Nagahama samples, and all Nagahama samples were clearly distinguished from natural eDNA samples from the other study sites. Symbols and colors indicate the purification protocol after the 1st PCR and experimental treatments, respectively. Ellipses indicate 95% confidential intervals for each study site and purification protocol.
](00_FormattedFigs/Figure_S05.pdf){width=100%}

</center>

